### ISSUE TITLE
完善readme文档的建议

### ISSUE THREAD

**Issue by 18801957105** [tencentyun/qcloud-iot-sdk-embedded-c#1]
希望README文档可以完善一点，增加常用平台编译和修改的步骤。

**Comment by shockcao** [comment]
@18801957105 我们正在完善版本，当前版本为内测试用版，即将在下周五发布新版本SDK
新版本会有完善的README文档及WiKi文档

**Comment by shockcao** [comment]
新版已发布 @18801957105
