### ISSUE TITLE
PSK密钥协商场景连接参数的设置

### ISSUE THREAD

**Issue by daishengdong** [tencentyun/qcloud-iot-sdk-embedded-c#11]
mqtt/src/mqtt_client.c   qcloud_iot_mqtt_init函数291、292行，这里在PSK密钥协商的场景下，也要设置CA证书信息么？

**Comment by daishengdong** [comment]
但是PSK场景下是不需要知道服务端的证书的吧？这里为什么还要设置一下？

**Comment by spikelin** [comment]
这里其实是拿根证书去验证云端的服务器证书。对于PSK场景，是可以选择做或者不做这一步的，所以把那两行注释掉也是可以运行的。
