### ISSUE TITLE
此处应该以返回值小于rc作为失败条件，而非等于0，因为IOT_MQTT_Publish返回的正值为包的编号。

### ISSUE THREAD

**Issue by jiaotilizi** [tencentyun/qcloud-iot-sdk-embedded-c#18]
https://github.com/tencentyun/qcloud-iot-sdk-embedded-c/blob/2536d8940131020fced2bb1f09a140e60dac0d0e/sdk-tests/multi_thread_test/multi_thread_test.c#L288

**Comment by spikelin** [comment]
是的，谢谢指正。应该以rc<0作为失败条件。不过packet-id在QoS0情况下是由调用者提供的，默认会是0.
另外原有的sdk-tests/multi_thread_test/multi_thread_test.c有些多线程问题，修复的版本放在samples/mqtt下面
