### ISSUE TITLE
是否可以返回特定的错误码呢？

### ISSUE THREAD

**Issue by jiaotilizi** [tencentyun/qcloud-iot-sdk-embedded-c#19]
https://github.com/tencentyun/qcloud-iot-sdk-embedded-c/blob/75b9f02a0f4d7cd3490f878472ae4695639a0c45/src/mqtt/src/mqtt_client_common.c#L1037

当sub返回正数（paket-id），消息回调挂接handles满了之后，希望返回特定错误码用于标识该特定的错误原因。eg：某场景下，设备主程序Yield循环期间，无法感知该错误类型，sub返回正数paket-id后，Yield不会触发sub handle回调函数，而仅仅返回-1001失败，设备开发人员无法知道是否该将该sub的主题放入自己的订阅list表中。

**Comment by spikelin** [comment]
可以在MQTT事件处理函数_mqtt_event_handler里面更新订阅状态变化，也可以通过新增加的IOT_MQTT_IsSubReady接口查询订阅是否成功
