### ISSUE TITLE
SDK支持多个子设备上线

### ISSUE THREAD

**Issue by weicao0** [tencentyun/qcloud-iot-sdk-embedded-c#20]
目前的GatewayParam结构体中只支持单个子设备名称，请提供多个子设备上线的接口。
如修改GatewayParam中char *subdev_device_name为char *subdev_device_name[]，并在内部实现中新增相关代码。

**Comment by spikelin** [comment]
gateway_sample示例演示了网关代理一个子设备的情况，如果用户需要增加更多子设备，可以先在控制台添加子设备，然后在代码里面通过创建更多GatewayParam参数实例，并将GatewayParam参数传递给网关各个API，即可以实现网关代理多个子设备进行通讯。
