### ISSUE TITLE
cmake选项通过命令行指定

### ISSUE THREAD

**Issue by wwwpf** [tencentyun/qcloud-iot-sdk-embedded-c#24]
现在的方式是直接在 `CMastLists.txt` 里 `set(BUILD_TYPE "release")`，如果我想写一个脚本编译，无法通过命令行重新设置变量，除非直接修改 `CMastLists.txt` 中变量的值，是否考虑使用缓存变量？

**Comment by spikelin** [comment]
暂不支持，如需要请自行修改源码
