### ISSUE TITLE
ESP8266平台无法连接到服务器

### ISSUE THREAD

**Issue by elitah** [tencentyun/qcloud-iot-sdk-embedded-c#28]
乐鑫SDK版本是v3.3(b74255d)

以下是调试信息：
INF|1970-01-01 00:00:06|qcloud_iot_device.c|iot_device_info_set(65): SDK_Ver: 3.1.3, Product_ID: R0UVGK0FR9, Device_Name: DEV000000000001
ERR|1970-01-01 00:00:06|HAL_TLS_mbedtls.c|HAL_TLS_Connect(256): mbedtls_ssl_handshake failed returned 0x7780(s)
ERR|1970-01-01 00:00:06|mqtt_client.c|IOT_MQTT_Construct(121): mqtt connect with id:  failed: -1001
INF|1970-01-01 00:00:06|mqtt_client.c|qcloud_iot_mqtt_fini(442): release mqtt client resources

**Comment by spikelin** [comment]
这个错误一般需要检查设备三元组信息是否正确配置。ESP8266平台移植示例请参考 https://github.com/tencentyun/qcloud-iot-esp-wifi/tree/master/qcloud-iot-esp8266-demo
