### ISSUE TITLE
FEATURE_AT_OS_USED 关闭 编译出错

### ISSUE THREAD

**Issue by PLAY233** [tencentyun/qcloud-iot-sdk-embedded-c#30]
MCU+通用TCP_AT模组移植(nonOS) 按照 所给文档配置CMakeLists.txt 编译报错
![image](https://user-images.githubusercontent.com/51319893/91701828-6c2bd100-ebaa-11ea-9211-3b6a47dcebdb.png)

查看代码发现resp_sem 被 FEATURE_AT_OS_USED 注释掉了
![image](https://user-images.githubusercontent.com/51319893/91701970-a72e0480-ebaa-11ea-8b8f-3f08ccad5204.png)

**Comment by spikelin** [comment]
已修复
