### ISSUE TITLE
关闭ATsocket时，未判断指针是否为NULL

### ISSUE THREAD

**Issue by xin5683** [tencentyun/qcloud-iot-sdk-embedded-c#32]
https://github.com/tencentyun/qcloud-iot-sdk-embedded-c/blob/5381d0efd99efe96337c29ecbdf64c3e40a1cb59/sdk_src/network/at_socket/at_socket_inf.c#L215-L227

如果_at_socket_find 获取返回为NULL，执行“pAtSocket->state = eSOCKET_CLOSED; ”，访问0地址会宕机。

**Comment by spikelin** [comment]
已修复
