### ISSUE TITLE
移植到嵌入式平台，有相关介绍吗？

### ISSUE THREAD

**Issue by JunCheung** [tencentyun/qcloud-iot-sdk-embedded-c#5]
文档里面只是介绍了SDK的代码结构，但是对于移植的具体操作没有说明啊，有没有具体的操作实例？
怎么设置编译参数，怎么选择编译平台等等。

**Comment by skyztmeng** [comment]
跨平台移植可以参考https://cloud.tencent.com/document/product/634/12515

**Comment by JunCheung** [comment]
这里只介绍了需要实现哪些函数，其他什么都没说明啊

**Comment by JunCheung** [comment]
我们想要移植到esp8266里面，应该是可以使用SDK的，Ali物联网平台已经移植后的有官方例程。
然而porting的介绍只有那么一点，目前编译出来是linux的一个mqtt_sample，那移植的时候应该怎么修改编译参数，最终编译出来的SDK在哪里。
感觉就是没经过实际移植的操作啊。

**Comment by spikelin** [comment]
请体验新版本。ESP8266的移植和示例请参考 https://github.com/tencentyun/qcloud-iot-esp-wifi/tree/master/qcloud-iot-esp8266-demo
